# Generated by Django 4.1.6 on 2023-04-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0002_service_phone_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mobile_app.service'),
        ),
    ]
