# Generated by Django 4.1.6 on 2023-05-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0007_types_apple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apple',
            name='service',
        ),
        migrations.AddField(
            model_name='apple',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mobile_app.types'),
        ),
    ]
