# Generated by Django 4.1.6 on 2023-05-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0008_remove_apple_service_apple_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
