# Generated by Django 4.1.6 on 2023-05-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0009_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=12999),
        ),
    ]
