# Generated by Django 4.1.6 on 2023-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0011_alter_phone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
